# -*- coding: utf-8 -*-
"""Compare_Excels.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vFcsbMdgFUQeMANAKk_dws5REkfEjUXu
"""

#!pip install xlwings

from pathlib import Path  # Core Python Module

import pandas as pd  # pip install pandas openpyxl
import xlwings as xw  # pip install xlwings

initial_version = Path.cwd() / "Source-file.xlsx"
updated_version = Path.cwd() / "Target-file.xlsx"

df_initial = pd.read_excel(initial_version)
print(df_initial.head(3))

df_update = pd.read_excel(updated_version)
print(df_update.head(3))

df_initial.shape

df_update.shape

df_initial.shape == df_update.shape

diff = df_update.compare(df_initial, align_axis=1)
diff
# self = updated_version
# other = initial_version

diff = df_update.compare(df_initial, align_axis=0)
diff

diff = df_update.compare(df_initial, keep_shape=True, keep_equal=False)
diff

diff = df_update.compare(df_initial, keep_shape=True, keep_equal=True)
diff

diff = df_update.compare(df_initial, keep_shape=True, keep_equal=True, align_axis=1, result_names=("Target", "Source"))
diff
diff.to_excel(Path.cwd() / "Difference.xlsx")

import openpyxl
from openpyxl.styles import PatternFill

def compare_and_highlight(file_path):
    # Load the Excel file
    wb = openpyxl.load_workbook(file_path)
    sheet = wb.active

    # Iterate through each row and compare "source" and "target" columns
    for row in sheet.iter_rows(min_row=4, max_row=sheet.max_row, min_col=1, max_col=sheet.max_column):
        for col in range(3, sheet.max_column, 2):
            if col + 1 <= sheet.max_column:
                source_value = row[col].value  # column index 3 in excel is 2 in 0-based index
                target_value = row[col + 1].value

                # Only apply color if the values are different
                if source_value != target_value:
                    # Set the fill color to red for differences
                    fill = PatternFill(start_color="FF0000", end_color="FF0000", fill_type="solid")
                    # Apply fill color to the pair of cells
                    row[col + 1].fill = fill
                    row[col].fill = fill

    # Save the changes
    wb.save(file_path)

# Example usage:
compare_and_highlight("Difference.xlsx")
