name: Add License File

on:
  workflow_dispatch:

jobs:
  add-license:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout central repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GK_PAT }}
          path: ${{ github.workspace }}/source-repo

      - name: Check if output directory exists
        run: |
            if [ ! -d "${{ github.workspace }}/source-repo/output" ]; then
              echo "Output directory does not exist. Creating..."
              mkdir -p "${{ github.workspace }}/source-repo/output"
            else
              echo "Output directory already exists."
            fi

      - name: Import GPG key
        run: |
          echo "${GPG_PRIVATE_KEY}" | gpg --batch --import
        env: 
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Add the custom gpg signing program that passes the passphrase to the gpg CLI
        run: |
            rm -rf /tmp/gpg.sh
            echo '#!/bin/bash' >> /tmp/gpg.sh
            echo 'gpg --batch --pinentry-mode=loopback --passphrase $GPG_KEY_PASSPHRASE $@' >> /tmp/gpg.sh
            chmod +x /tmp/gpg.sh
  
      - name: Setup git
        run: |
            git config --global user.email ${{ secrets.GIT_COMMITTER_EMAIL }}
            git config --global user.name ${{ secrets.GIT_COMMITTER_NAME }}
            git config --global commit.gpgsign true
            git config --global user.signingkey $GPG_KEY_ID
            git config --global gpg.program /tmp/gpg.sh
        env:
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}

      - name: Iterate Over Repos
        run: |
          mapfile -t repositories < <(awk '{print $1}' "${{ github.workspace }}/source-repo/data/repositories.txt")
          for repo in "${repositories[@]}"; do
            echo "Processing repository: $repo"

            # Get default branch using GitHub API
            default_branch=$(curl -s -H "Authorization: token ${{ secrets.GK_PAT }}" "https://api.github.com/repos/$repo" | jq -r .default_branch)

            echo "Default branch for $repo is $default_branch"

            # Clone default branch to check for LICENSE file
            git clone --depth 1 -b "$default_branch" "https://${{ secrets.GK_PAT }}@github.com/$repo.git" "./default-branch-repo"

            # Check if LICENSE file exists in default branch
            if [ ! -f "./default-branch-repo/LICENSE" ]; then
              echo "LICENSE file does not exist in the default branch. Proceeding to add it to the github-migration branch."

              # Clone target repository's github-migration branch
              git clone --depth 1 -b "github-migration" "https://${{ secrets.GK_PAT }}@github.com/$repo.git" "./target-repo"

              # Copy LICENSE file from source to target repository
              if cp "${{ github.workspace }}/source-repo/data/LICENSE" "./target-repo/LICENSE" >> "${{ github.workspace }}/source-repo/output/add-license-file-errors.txt" 2>&1; then
                echo "LICENSE file copied successfully."
                echo "$repo;License File Copied Successfully." >> "${{ github.workspace }}/source-repo/output/add-license-file.txt"
              else
                error_message=$(tail -n 1 "${{ github.workspace }}/source-repo/output/add-license-file-errors.txt")
                echo "Error: Failed to copy LICENSE file."
                echo "$repo;Failed to Copy License File. ; $error_message" >> "${{ github.workspace }}/source-repo/output/add-license-file.txt"
              fi
              
              # Stage and commit the changes for target repository
              cd "./target-repo"
              if [ -n "$(git status --porcelain)" ]; then
                  git pull origin github-migration
                  git add LICENSE
                  git commit -S -m "Add LICENSE File - $(date +"%Y-%m-%d %H:%M:%S")" 
                  git push origin github-migration
              else
                  echo "No changes to commit."
              fi
            else
              echo "LICENSE file already exists in the default branch."
              echo "$repo ; License File Already Exists in Default Branch." >> "${{ github.workspace }}/source-repo/output/add-license-file.txt"
            fi

            # Update output file in central repository
            # cd "${{ github.workspace }}/source-repo/output"
            # if [ -n "$(git status --porcelain)" ]; then
            #     git pull origin main
            #     git add add-license-file.txt
            #     git commit -S -m "Add Output File - $(date +"%Y-%m-%d %H:%M:%S")" 
            #     git push origin main
            # else
            #     echo "No changes to commit."
            # fi

            # Clean up
            cd ..
            rm -rf "./default-branch-repo" "./target-repo"
          done
        env:
          GPG_KEY_PASSPHRASE: ${{ secrets.PASSPHRASE }}

      - name: Upload License File Check Output
        uses: actions/upload-artifact@v4
        with:
            name: license_file_report
            path: ${{ github.workspace }}/source-repo/output     
