name: Trigger Repository Workflows

on:
  issues:
    types:
      - opened
      - edited

# expected issue body input should be structured as follows:
  #     {
  #         "rep01": {
  #             "repository": "rep01",
  #             "organisation": "org01"
  #         },
  #         "rep02": {
  #             "repository": "rep02",
  #             "organisation": "org02"
  #         } 
  #     }

jobs:
  trigger-repo-workflows:
    if: contains(github.event.issue.labels.*.name, 'post-mg-steps')
    runs-on: ubuntu-latest
    strategy:  
      matrix:
        repository: ${{ fromJson(github.event.issue.body).*.repository }}  # rep01, repo02
      max-parallel: 1
    steps:
      - name: Trigger Organization Change Workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GK_PAT}}
          script: |
            const response = await github.rest.actions.createWorkflowDispatch({
              owner: '${{ fromJSON(github.event.issue.body)[matrix.repository].organisation }}',
              repo: '${{ matrix.repository}}',
              workflow_id: 'replace-string-all.yml', 
              ref: 'github-migration'  
            });
            console.log(response.data);

      - name: Acknowledgment For Runner Change
        uses: actions/github-script@v6
        with:
          script: |
            const response = github.request(
              'POST /repos/{owner}/{repo}/issues/{issue_number}/comments',
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: '${{ github.event.issue.number }}',
                body: 'Starting Runner Change for `${{ matrix.repository}}`.....',
                headers: {
                  'X-GitHub-Api-Version': '2022-11-28'
                }
              }
            );