name: Update Runner

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Target Branch'
        required: true

jobs:
  setup-commit-signing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
            token: ${{ secrets.GK_PAT }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
            gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
            passphrase: ${{ secrets.PASSPHRASE }}
      
      - name: Add the custom gpg siging program that passes the passphrase to the gpg CLI
        run: |
            rm -rf /tmp/gpg.sh
            echo '#!/bin/bash' >> /tmp/gpg.sh
            echo 'gpg --batch --pinentry-mode=loopback --passphrase $GPG_KEY_PASSPHRASE $@' >> /tmp/gpg.sh
            chmod +x /tmp/gpg.sh

      - name: Setup git
        run: |
            git config commit.gpgsign true
            git config user.signingkey $GPG_KEY_ID
            git config gpg.program /tmp/gpg.sh
        env:
            GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}

      - name: Create and Checkout New Branch
        run: |
            git checkout -b ${{ github.event.inputs.branch }}  # Replace 'branch-name' with the desired branch name
        working-directory: ${{ github.workspace }}

      - name: Replace Strings in Workflow Files
        run: |
            for file in $(find .github/workflows -name '*.yml' -not -name 'commit-signing.yml'); do
            sed -i 's/ubuntu-latest/windows-latest/g' "$file"
            done

      - name: Commit Changes
        run: |
            git config user.email ${{ secrets.GIT_COMMITTER_EMAIL }}
            git config user.name ${{ secrets.GIT_COMMITTER_NAME }}
            git add .
            git commit -m "Replace runs-on parameter"
            git push -u origin ${{ github.event.inputs.branch }}  # Replace 'branch-name' with the branch name
        working-directory: ${{ github.workspace }}
        env:
            GITHUB_TOKEN: ${{ secrets.GK_PAT }}

      #- name: Push Changes to New Branch
      #  run: |
       #     git push --set-upstream origin github-migration  # Replace 'branch-name' with the branch name
        #working-directory: ${{ github.workspace }}
        #env:
           # GITHUB_TOKEN: ${{ secrets.GK_PAT }}

         #echo "ORG: ${{ github.event.repository.owner.name }}"
         #echo "Repo: $GITHUB_REPOSITORY"
         #git remote set-url origin https://x-access-token:${{ secrets.GK_PAT }}@github.com/${{ github.repository }}.git