name: Distribute YML Files

on:
  push

jobs:
  distribute-yml-files:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout central repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Copy YML Files
        run: |
            owner="github-gk-aks"
            repo="firstgithubrepo"
            echo "Processing repository: $owner/$repo"
            workflow_file=".github/workflows/github-rest-api123.yml"

            content=$(cat files/github-rest-api123.yml)  # Update this if your YML file is in a different location

            curl -X PUT \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${{ secrets.GK_PAT }}" \
              "https://api.github.com/repos/$owner/$repo/contents/$workflow_file" \
              -d @- <<EOF
            {
              "message": "Update $workflow_file",
              "content": "$(echo -n "$content")",
              "branch": "github-migration"
            }
            EOF

