name: Distribute YML Files

on:
  push

jobs:
  distribute-yml-files:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Copy YML Files
        run: |
            repo="github-gk-aks/firstgithubrepo"
            echo "Processing repository: $repo"
            workflow_file=".github/workflows/github-rest-api123.yml"
            content=$(cat files/github-rest-api123.yml)  # Update this if your YML file is in a different location

            curl -X PUT \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/$repo/contents/$workflow_file" \
              -d @- <<EOF
            {
              "message": "Update $workflow_file",
              "content": "$(echo -n "$content" | base64)",
              "branch": "github-migration"
            }
            EOF

