name: Repository Object Count

on:
    workflow_dispatch
#   issues:
#     types:
#       - opened
#       - edited

# expected issue body input should be structured as follows:
  #     {
  #         "rep01": {
  #             "repository": "rep01",
  #             "organisation": "org01"
  #         },
  #         "rep02": {
  #             "repository": "rep02",
  #             "organisation": "org02"
  #         } 
  #     }

jobs:
  count-repository-objects:
    # if: contains(github.event.issue.labels.*.name, 'repo-obj-count')
    runs-on: ubuntu-latest
    # strategy:  
    #   matrix:
    #     repository: ${{ fromJson(github.event.issue.body).*.repository }}  # rep01, repo02
    #   max-parallel: 1
    steps:
      - name: Commit Count
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GK_PAT}}
          script: |
                let totalCommits = 0;
                let page = 1;
                let perPage = 100;
                while (true) {
                const commits = await github.rest.repos.listCommits({
                    owner: 'github-gk-aks',
                    repo: 'firstgithubrepo',
                    per_page: perPage,
                    page: page++
                });
                if (commits.data.length === 0) break;
                totalCommits += commits.data.length;
                }
                console.log('Total Commits:', totalCommits);

      - name: Open Issues Count
        uses: actions/github-script@v6
        with:   
           github-token: ${{ secrets.GK_PAT }}
           script: |
                // let totalCommits = 0;
                // let page = 1;
                // let perPage = 100;
                // while (true) {
                const openIssues = await github.rest.issues.listForRepo({
                    owner: 'github-gk-aks',
                    repo: 'firstgithubrepo',
                    state: 'Open'
                    #per_page: perPage,
                    #page: page++
                });
                // if (commits.data.length === 0) break;
                // totalCommits += commits.data.length;
                // }
                console.log('Total Open Issues:', openIssues.data.length);