name: Automated PRs with Dynamic Reviewers

on:
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install @octokit/rest

    - name: Read Reviewers from File
      id: read_reviewers
      run: |
        REVIEWERS_FILE="data/reviewers.txt"
        mapfile -t repositories < "$REVIEWERS_FILE"
        for repo in "${repositories[@]}"; do
            IFS='/' read -r org_name repo_name <<< "$repo"
            echo "Processing repository: $org_name/$repo_name"
        done  
        #REVIEWERS=$(cat "$REVIEWERS_FILE" | tr -d '\r')
        #echo "REVIEWERS: $REVIEWERS"
        #IFS=$'\n' read -ra REVIEWER_ARRAY <<< "$REVIEWERS"
        readarray -t REVIEWER_ARRAY < "$REVIEWERS_FILE"

        for reviewer in "${REVIEWER_ARRAY[@]}"; do
            echo "Reviewer: $reviewer"
        done
        for i in "${REVIEWER_ARRAY[@]}"; do
            IFS=' ' read -ra REPO_REVIEWER <<< "$i"
            if [[ "${REPO_REVIEWER[0]}" == "repo1" ]]; then
                reviewers="${REPO_REVIEWER[@]:1}"  # Select all elements from index 1 to the end
                echo "Final reviewers: $reviewers"
            fi
        done

        
        #echo "::set-output name=reviewers::$REVIEWERS"

    # - name: Create Pull Request
    #   run: |
    #     # Set up your GitHub token as a secret in your repository
    #     GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}

    #     npm install -g @octokit/rest
    #     PR_URL=$(octokit pr create \
    #       --base main \
    #       --head feature-branch \
    #       --title "Automated PR" \
    #       --body "Your pull request description" \
    #       --token $GITHUB_TOKEN | jq -r '.url')

    #     # Read reviewers dynamically
    #     REVIEWERS="${{ steps.read_reviewers.outputs.reviewers }}"
    #     IFS=' ' read -ra REVIEWER_ARRAY <<< "$REVIEWERS"

    #     # Loop through reviewers and add them to the pull request
    #     for i in "${REVIEWER_ARRAY[@]}"; do
    #         IFS=':' read -ra REPO_REVIEWER <<< "$i"
    #         if [[ "${REPO_REVIEWER[0]}" == "$(basename $GITHUB_REPOSITORY)" ]]; then
    #         reviewers="${REPO_REVIEWER[@]:1}"  # Select all elements from index 1 to the end
    #         octokit pr create-review-request \
    #             --reviewers $reviewers \
    #             --token $GITHUB_TOKEN \
    #             --request-url $PR_URL
    #       fi
    #     done

    #     # If you want to use a different user for commit, you might need to set the git user information here

    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}