name: Create New Branch in Repos

on:
  issues:
    types:
      - opened
      - edited

# expected issue body input should be structured as follows:
  #     {
  #         "rep01": {
  #             "repository": "rep01",
  #             "organisation": "org01"
  #         },
  #         "rep02": {
  #             "repository": "rep02",
  #             "organisation": "org02"
  #         } 
  #     }

jobs:
  trigger-repo-workflows:
    if: contains(github.event.issue.labels.*.name, 'branch-creation')
    runs-on: ubuntu-latest
    strategy:  
      matrix:
        repository: ${{ fromJson(github.event.issue.body).*.repository }}  # rep01, repo02
      max-parallel: 1
    steps:
      - name: Acknowledgment For Runner Change
        uses: actions/github-script@v6
        with:
          script: |
            const response = github.request(
              'POST /repos/{owner}/{repo}/issues/{issue_number}/comments',
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: '${{ github.event.issue.number }}',
                body: 'Creating new branch for `${{ matrix.repository}}`.....',
                headers: {
                  'X-GitHub-Api-Version': '2022-11-28'
                }
              }
            );        

      - name: Checkout Central Repository
        uses: actions/checkout@v4

    #   - name: Create branch
    #     run: |
    #       REPO_NAME="${{ matrix.repository }}"
    #       BRANCH_NAME="test-branch"
    #       curl -X POST \
    #         -H "Accept: application/vnd.github.v3+json" \
    #         -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
    #         https://api.github.com/repos/${{ fromJSON(github.event.issue.body)[matrix.repository].organisation }}/$REPO_NAME/git/refs \
    #         -d '{
    #           "ref": "refs/heads/'"$BRANCH_NAME"'",
    #           "sha": "$(git rev-parse HEAD)"
    #         }'
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create branch
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GK_PAT }}
          script: |
            await github.rest.git.createRef({
             owner: '${{ fromJSON(github.event.issue.body)[matrix.repository].organisation }},
             repo: '${{ matrix.repository }}',
             ref: 'refs/heads/test-branch',
             sha: context.sha
            });

