name: Create PRs with Dynamic Reviewers

on:
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GK_PAT }}
        path: ./source-repo

    - name: Check if output directory exists
      run: |
        if [ ! -d "${{ github.workspace }}/source-repo/output" ]; then
          echo "Output directory does not exist. Creating..."
          mkdir -p "${{ github.workspace }}/source-repo/output"
        else
          echo "Output directory already exists."
        fi

    - name: Read Reviewers from File
      id: read_reviewers
      run: |
        REVIEWERS_FILE="${{ github.workspace }}/source-repo/data/reviewers.txt"
        mapfile -t repositories < <(awk '{print $1}' "$REVIEWERS_FILE" | sort -u)
        # So, in summary, the entire statement reads the content of the reviewers file, 
        # extracts the first column (repository names) from each line, sorts them alphabetically,
        # removes any duplicate names, and stores them in the repositories array for further processing.

        for repo in "${repositories[@]}"; do
            IFS='/' read -r org_name repo_name <<< "$repo"
            echo "Processing repository: $org_name/$repo_name"
        
            default_branch=$(git ls-remote --symref https://github.com/$repo HEAD | awk -F '/' '/^ref:/{print $NF}' | awk '{print $1}')

            echo "Default Branch is $default_branch"

            http_status_and_response=$(curl -w "%{http_code}\n" -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.GK_PAT }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/$repo/pulls \
                -d '{"title":"Migrating Changes","body":"Please pull these migration related changes","head":"github-migration","base":"'"$default_branch"'"}')

            #echo "The response is : $http_status_and_response"

            http_status=$(echo "$http_status_and_response" | tail -n 1)
            pr_response=$(echo "$http_status_and_response" | sed '$d')

            if [[ $http_status == 201 ]]; then
                pr_number=$(echo "$pr_response" | jq -r '.number')
                echo "Pull Request created successfully. Number: $pr_number"

                #REVIEWERS=$(awk -v repo="$repo" '$1 == repo { print $2 }' "$REVIEWERS_FILE")
                #REVIEWERS=$(awk -v repo="$repo" '$1 == repo { gsub("\r",""); print substr($0, length($1)+2) }' "$REVIEWERS_FILE")
                REVIEWERS=$(awk -v repo="$repo" '$1 == repo { print substr($0, length($1)+2) }' "$REVIEWERS_FILE")
                IFS=' ' read -ra REVIEWER_ARRAY <<< "$REVIEWERS"
                # for reviewer in "${REVIEWER_ARRAY[@]}"; do
                #    echo "Reviewer: $reviewer"
                # done

                # Add reviewers to the pull request
                http_status_and_response_reviewers=$(curl -w "%{http_code}\n" -L \
                    -X POST \
                    -H "Accept: application/vnd.github+json" \
                    -H "Authorization: Bearer ${{ secrets.GK_PAT }}" \
                    -H "X-GitHub-Api-Version: 2022-11-28" \
                    "https://api.github.com/repos/$repo/pulls/$pr_number/requested_reviewers" \
                    -d '{"reviewers":['$(printf '"%s",' "${REVIEWER_ARRAY[@]}" | sed 's/,$//')']}')

                http_status_reviewers=$(echo "$http_status_and_response_reviewers" | tail -n 1)
                reviewers_response=$(echo "$http_status_and_response_reviewers" | sed '$d')

                if [[ $http_status_reviewers == 201 ]]; then
                    echo "Reviewers added successfully to the Pull Request."
                    echo "$repo ; Pull Request with number $pr_number Created Successfully with status code $http_status ; Reviewers added successfully with status code $http_status_reviewers" >> "${{ github.workspace }}/source-repo/output/create-pr-output.txt"
                else
                    echo "Failed to add reviewers to the Pull Request. HTTP Status: $http_status_reviewers"
                    echo "Response body: $reviewers_response"
                    echo "$repo ; Pull Request with number $pr_number Created Successfully with status code $http_status ; Failed to add reviewers to the Pull Request. HTTP Status is $http_status_reviewers ; Response body is $reviewers_response" >> "${{ github.workspace }}/source-repo/output/create-pr-output.txt"
                fi
            else
                if [[ $http_status == 422 ]]; then
                  echo "A pull request already exists for the repository."
                  echo "$repo ; A pull request already exists for the repository." >> "${{ github.workspace }}/source-repo/output/create-pr-output.txt"
                else
                  echo "Failed to create Pull Request. HTTP Status: $http_status"
                  echo "Response body: $pr_response"
                  echo "$repo ; Failed to create Pull Request. HTTP Status is $http_status ; Response body is $reviewers_response" >> "${{ github.workspace }}/source-repo/output/create-pr-output.txt"
                fi
                continue  # Continue to the next repository
            fi

        # #REVIEWERS=$(cat "$REVIEWERS_FILE" | tr -d '\r')
        # #echo "REVIEWERS: $REVIEWERS"
        # #IFS=$'\n' read -ra REVIEWER_ARRAY <<< "$REVIEWERS"
        # readarray -t REVIEWER_ARRAY < "$REVIEWERS_FILE"

        # # for reviewer in "${REVIEWER_ARRAY[@]}"; do
        # #     echo "Reviewer: $reviewer"
        # # done
        # for i in "${REVIEWER_ARRAY[@]}"; do
        #     IFS=' ' read -ra REPO_REVIEWER <<< "$i"
        #         reviewers="${REPO_REVIEWER[@]:1}"  # Select all elements from index 1 to the end
        #         echo "Final reviewers: $reviewers"
         
        # done
        done

    - name: Commit Changes
      run: |
          cd ${{ github.workspace }}/source-repo/output
          git config user.email ${{ secrets.GIT_COMMITTER_EMAIL }}
          git config user.name ${{ secrets.GIT_COMMITTER_NAME }}
          git add create-pr-output.txt
          git commit -m "Add create-pr-output.txt - $(date +"%Y-%m-%d %H:%M:%S")" 
          git push
      working-directory: ${{ github.workspace }}