name: Fetch Repositories

on:
  workflow_dispatch:

jobs:
  fetch-repos:
    runs-on: ubuntu-latest
    env:
        GK_PAT: ${{ secrets.GK_PAT }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Fetch Repositories
      run: python files/fetch_repos.py

    - name: Display Repo List
      run: cat repo_list.txt
