name: Check Code Owners

on:
 workflow_dispatch:

jobs:
 check-code-owners:
   runs-on: ubuntu-latest
   env:
    GK_PAT: ${{ secrets.GK_PAT }}
   steps:
   - name: Checkout this repository
     uses: actions/checkout@v4
     with:
        token: ${{ secrets.GK_PAT }}

   - name: Set up Python
     uses: actions/setup-python@v2
     with:
       python-version: 3.x

   - name: Install dependencies
     run: |
       python -m pip install --upgrade pip
       pip install openpyxl  # For Excel file support
       pip install requests

   - name: Run Python script
     run: python files/check_code_owners.py

   - name: Upload results.txt as artifact
     uses: actions/upload-artifact@v4
     with:
      name: results
      path: results.txt

 commit-results:
   needs: check-code-owners
   runs-on: ubuntu-latest
   steps:
   - name: Checkout this repository
     uses: actions/checkout@v4

   - name: Download results.txt artifact
     uses: actions/download-artifact@v4
     with:
        name: results
        path: ./  # Download to the current directory

   - name: Commit results.txt back to the repository
     run: |
        git config user.email ${{ secrets.GIT_COMMITTER_EMAIL }}
        git config user.name ${{ secrets.GIT_COMMITTER_NAME }}
        git add results.txt
        git commit -m "Add results.txt"
        git push     