name: Check Code Owners

on:
 workflow_dispatch:

jobs:
 check-code-owners:
   runs-on: ubuntu-latest
   env:
    GK_PAT: ${{ secrets.GK_PAT }}
   steps:
   - name: Checkout this repository
     uses: actions/checkout@v4
     with:
        token: ${{ secrets.GK_PAT }}

   - name: Set up Python
     uses: actions/setup-python@v2
     with:
       python-version: 3.x

   - name: Install dependencies
     run: |
       python -m pip install --upgrade pip
       pip install openpyxl  # For Excel file support
       pip install requests

   - name: Run Python script
     run: python files/check_code_owners.py

   - name: Upload result_codeowners.txt as artifact
     uses: actions/upload-artifact@v4
     with:
      name: results
      path: output/result_codeowners.txt

 commit-results:
   needs: check-code-owners
   runs-on: ubuntu-latest
   steps:
   - name: Checkout this repository
     uses: actions/checkout@v4

   - name: Download result_codeowners.txt artifact
     uses: actions/download-artifact@v4
     with:
        name: result_codeowners.txt
        path: ./output  # Download to the current directory

   - name: Commit result_codeowners.txt back to the repository
     run: |
        git config user.email ${{ secrets.GIT_COMMITTER_EMAIL }}
        git config user.name ${{ secrets.GIT_COMMITTER_NAME }}
        git pull origin main
        git add result_codeowners.txt
        git commit -m "Add result_codeowners.txt"
        git push origin main  