name: Fetch Teams and Members

on:
  workflow_dispatch:

jobs:
  fetch-teams-members:
    runs-on: ubuntu-latest
    env:
        GK_PAT: ${{ secrets.GK_PAT }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GK_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openpyxl requests

      - name: Fetch Teams and Members
        run: python files/fetch_team_members.py

      - name: Commit results.txt back to the repository
        run: |
            git config user.email ${{ secrets.GIT_COMMITTER_EMAIL }}
            git config user.name ${{ secrets.GIT_COMMITTER_NAME }}
            git pull
            git add teams_members_permissions.xlsx
            git commit -m "Add teams_members_permissions.xlsx - $(date +"%Y-%m-%d %H:%M:%S")"
            git push    

