name: Get Repo Size

on:
    issues:
      types:
        - opened
        - edited
  
  # expected issue body input should be structured as follows:
    #     {
    #         "rep01": {
    #             "repository": "rep01",
    #             "organisation": "org01"
    #         },
    #         "rep02": {
    #             "repository": "rep02",
    #             "organisation": "org02"
    #         } 
    #     }
  

jobs:
  trigger-repo-workflows:
      if: contains(github.event.issue.labels.*.name, 'get-repo-size')
      runs-on: ubuntu-latest
      env:
        GK_PAT: ${{ secrets.GK_PAT }}
      strategy:  
        matrix:
            repository: ${{ fromJson(github.event.issue.body).*.repository }}  # rep01, repo02
        max-parallel: 10
        fail-fast: false

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.x'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install requests

        - name: Run Python script
          run: python ${{ github.workspace }}/files/check_repo_size.py "${{ matrix.repository }}" "${{ fromJSON(github.event.issue.body)[matrix.repository].organisation }}"
       
        - name: Upload repo migration status
          uses: actions/upload-artifact@v3
          with:
            name: statuses_repo_size
            path: ${{ github.workspace }}/report_${{ matrix.repository }}.txt

        
