name: Grant Repository Access to Org Secrets

on:
  workflow_dispatch:
    # inputs:
    #   secret_name:
    #     description: 'The name of the org secret'
    #     required: true
    #   organization:
    #     description: 'Name of the organization'
    #     required: true

jobs:
  grant-access:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Grant access to repositories
      env:
        GH_TOKEN: ${{ secrets.GK_PAT }}
      run: |
        mapfile -t secrets < "${{ github.workspace }}/secrets.txt"
        mapfile -t repositories < <(awk '{print $1}' "${{ github.workspace }}/repositories.txt" | sort -u)
        for secret in "${secrets[@]}"; do
          echo "Processing secret: $secret"
            for repo in "${repositories[@]}"; do
                IFS='/' read -r org_name repo_name <<< "$repo"
                echo "Processing repository: $repo"
                echo "Granting access to $repo_name"
                # Fetch the repository ID
                repo_id=$(curl -H "Authorization: Bearer $GH_TOKEN" -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/$org_name/$repo_name | jq '.id')
                echo "Repository ID: $repo_id"

                # Grant access to the repository
                response=$(curl -X PUT -o /dev/null -w "%{http_code}" -s \
                    -H "Authorization: Bearer $GH_TOKEN" \
                    -H "Accept: application/vnd.github+json" \
                    -H "X-GitHub-Api-Version: 2022-11-28" \
                    https://api.github.com/orgs/$org_name/actions/secrets/$secret/repositories \
                    -d "{\"selected_repository_ids\": [$repo_id]}")

                echo "HTTP Status: $response"

                if [ "$response" -eq 204 ]; then
                    echo "Successfully granted access to $repo_name"
                else
                    echo "Failed to grant access to $repo_name with status $response"
                fi

                # curl -X PUT \
                #     -H "Authorization: Bearer $GH_TOKEN" \
                #     -H "Accept: application/vnd.github+json" \
                #     -H "X-GitHub-Api-Version: 2022-11-28" \
                #     https://api.github.com/orgs/$org_name/actions/secrets/$SECRET_NAME/repositories \
                #     -d "{\"selected_repository_ids\": [$(curl -H \"Authorization: Bearer $GH_TOKEN\" https://api.github.com/repos/$org_name/$repo_name | jq '.id')]}"

            done
        done