name: Grant Access to Org Secrets

on:
  workflow_dispatch:
    inputs:
      secret_name:
        description: 'The name of the org secret'
        required: true
    #   repositories:
    #     description: 'Comma-separated list of repository names'
    #     required: true

jobs:
  grant-access:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Grant access to repositories
      env:
        GH_TOKEN: ${{ secrets.GK_TOKEN }}
      run: |
        mapfile -t repositories < <(awk '{print $1}' "${{ github.workspace }}/source-repo/data/replacements_access-token.txt" | sort -u)
        for repo in "${repositories[@]}"; do
            echo "Processing repository: $repo"
            SECRET_NAME=${{ github.event.inputs.secret_name }}
            echo "Granting access to $REPO"
            curl -X PUT \
                -H "Authorization: token $GH_TOKEN" \
                -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/orgs/YOUR_ORG_NAME/actions/secrets/$SECRET_NAME/repositories \
                -d "{\"selected_repository_ids\": [$(curl -H \"Authorization: token $GH_TOKEN\" https://api.github.com/repos/YOUR_ORG_NAME/$repo | jq '.id')]}"

        done