name: Replace CODEOWNERS Teams

on:
  workflow_dispatch:

jobs:
  replace-teams:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GK_PAT }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openpyxl

    - name: Replace Teams
      run: |
        python replace_teams.py
