name: Replace CODEOWNERS Teams

on:
  workflow_dispatch:

jobs:
  replace-teams:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GK_PAT }}

    # - name: Copy Excel files to runner's workspace
    #   run: |
    #     mkdir -p $GITHUB_WORKSPACE/data
    #     cp data/CodeOwners-File-Location.xlsx $GITHUB_WORKSPACE/data
    #     cp data/CodeOwners-Team-Replacement.xlsx $GITHUB_WORKSPACE/data

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openpyxl PyGithub

    - name: Replace Teams
      run: |
        python files/replace_teams.py
