name: Replace Teams in CODEOWNERS

on:
  issues:
    types:
      - opened
      - edited

jobs:
  replace-teams:
    if: contains(github.event.issue.labels.*.name, 'codeowner-replace')
    runs-on: ubuntu-latest

    strategy:
      matrix:
        repository: ${{ fromJson(github.event.issue.body).*.repository }}
      max-parallel: 1

    steps:
      - name: Checkout central repository
        uses: actions/checkout@v4
        with:
            token: ${{ secrets.GK_PAT }}

      - name: Read Teams from Excel File
        id: read-teams
        run: |
          python -m pip install openpyxl
          python files/read_teams.py

      - name: Show Teams Output
        run: |
          echo "TEAMS: ${{ steps.read-teams.outputs.teams }}"

      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: "${{ fromJSON(github.event.issue.body)[matrix.repository].organisation}}/${{ matrix.repository }}"
          path: "./target-repo"
          token: ${{ secrets.GK_PAT }}

      - name: Replace Teams in CODEOWNERS
        run: |
          export CODEOWNERS_LOCATION='${{ fromJSON(github.event.issue.body)[matrix.repository].codeownerslocation }}'
          export TEAMS="${{ steps.read-teams.outputs.teams }}"
          export TEAMS="${TEAMS//\'/\"}"
          python files/replace_teams.py

      - name: Commit and Push Changes
        run: |
          cd ./target-repo
          git config user.email ${{ secrets.GIT_COMMITTER_EMAIL }}
          git config user.name ${{ secrets.GIT_COMMITTER_NAME }}
          git pull
          git add .
          git commit -m "Replace teams in CODEOWNERS - $(date +"%Y-%m-%d %H:%M:%S")"
          git push
