name: Migrate One or More Organisation Secrets

on:
  issues:
    types:
      - opened
      - edited
  # expected issue body input should be structured as follows:
  # {
  #     "01": {
  #         "secretname": "01",
  #         "visibility": "all",
  #         "destination": "targetorganization-a",
  #         "destinationPersonalAccessTokenName":"the_pat_a",
  #         "selected-repository-ids": []
  #     },
  #     "02": {
  #         "secretname": "02",
  #         "visibility": "selected",
  #         "destination": "targetorganization-b",
  #         "destinationPersonalAccessTokenName":"the_pat_b" ,
  #         "selected-repository-ids": [ "repo-id-1", "repo-id-2", ...]
  #     },
  #     ...
  # }

jobs:
  migrate-org-secret:
    if: contains(github.event.issue.labels.*.name, 'migrate-org-secret')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    strategy:
      matrix:
        secretname: ${{ fromJSON(github.event.issue.body).*.secretname }} # e.g. [ "01", "02", ...]
      max-parallel: 1
    steps:
      - name: Acknowledgement
        uses: actions/github-script@v6
        with:
          script: |

            const response = github.request (
              'POST /repos/{owner}/{repo}/issues/{issue_number}/comments',
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: '${{ github.event.issue.number }}',
                body: 'Migrating secret: `${{ matrix.secretname }}`...',
                headers: {
                  'X-GitHub-Api-Version': '2022-11-28'
                }
              }
            );
      - name: Save organisation secret
        uses: gh-gei-bells/github-secret/save-to-organization@main
        with:
          secret-name: ${{ matrix.secretname }} # e.g. "01"
          secret-value: ${{ secrets[matrix.secretname] }}
          secret-visibility: ${{ fromJSON(github.event.issue.body)[matrix.secretname].visibility }} # e.g. "all"
          destination-organization: ${{ fromJSON(github.event.issue.body)[matrix.secretname].destination }} # e.g. "targetorganization-a"
          destination-github-token: ${{ secrets[fromJSON(github.event.issue.body)[matrix.secretname].destinationPersonalAccessTokenName] }} # e.g. secret["the_pat_a"]
          destination-selected-repository-ids: ${{ join(fromJSON(github.event.issue.body)[matrix.secretname].selected-repository-ids) }} # e.g. "repo-id-1,repo-id-2",...